#!/bin/bash

# Analysis script: conformational analysis with rmsd matrix
if [ $# -ne 3 ]  && [ $# -ne 4 ] ; then 
	echo "syntax: $0 protein_name ligand_name confname [production_length: 20ns]"
	echo "(suposing that the filenames are strictly based on the protein and ligand names)"
	exit
fi

PROTEIN="$1"
LIGAND="$2"
EXT="-$3"
echo "Protein = $1  and Ligand = $2${EXT}"
if [ -d complex_${PROTEIN}_${LIGAND}${EXT} ] ; then
	echo "Entering complex_${PROTEIN}_${LIGAND}${EXT}"
	cd complex_${PROTEIN}_${LIGAND}${EXT}
else
	echo "The directory complex_${PROTEIN}_${LIGAND}${EXT} doesn't exist.... Exiting"
	exit
fi

if [ $# -eq 4 ] ; then 
	cd production-$4
else
	cd production
fi

if [ -d rmsd ] ; then
	echo "The rmsd directory already exists.... Exiting"
	exit
fi
mkdir rmsd
cd rmsd

printf "13 & ! a H*\n q\n" | gmx make_ndx -f ../confstart-center.gro
printf "4\n 13\n" | gmx rms -f ../traj_centpro.xtc -s ../topol.tpr  -n -m -dt 200
gmx xpm2ps -f rmsd.xpm

printf "4\n 13\n" | gmx rms -f ../traj_centpro.xtc -s ../topol.tpr  -n -m rmsd-big.xpm -o rmsd-big.xvg -dt 20
gmx xpm2ps -f rmsd-big.xpm -o rmsd-big.eps

